# Generated by Django 5.2 on 2025-04-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='care',
            options={'ordering': ['-date']},
        ),
    ]
