# Generated by Django 5.2 on 2025-04-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_supply_alter_care_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='supplies',
            field=models.ManyToManyField(to='main_app.supply'),
        ),
    ]
